### ISSUE TITLE
KeyError: 'a1245'

### ISSUE THREAD

**Issue by mattd624** [richardandersson/EAC#1]
Hi,
My wife is trying to use your EAC-100 python program to analyze some ELAN data, and I was able to install python 2.7 and the necessary modules, and make the program come up and read one of her .eaf files. But when I click analyze I get this error message:C:/Users/Installers/Dropbox/UOP/Research Methods/Intonation and cospeech gesture/Media files/A - Complete/A - Tones Complete/FeNi_Ocean/Ocean_final.eaf
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1547, in __call__
    return self.func(*args)
  File "EAC100.py", line 386, in analyzeFiles
    processTCA()
  File "EAC100.py", line 598, in processTCA
    ptime = timeslots[align_id.group(1)]
KeyError: 'a1245'
She is trying to get correlation data between dysfluency, tone, and hand/head/body movements. We are not exactly sure if this program does what we need, but we were hoping to see what it can do. Can you help? I know a little bit of python, but I have never written, much less debugged anything this extensive. Thanks for any insight or help you can provide. 

Here's a link to the eaf file involved:
https://www.dropbox.com/s/ojoppjorddzz7p2/Ocean_final.eaf?dl=0

--Matt

**Comment by richardandersson** [comment]
Hi,

Thanks for your interest!
Let me just state up front that I have not used this software for quite some time. There are many things I would have done different if I did it today, and there is a lot of room for improvement. So I will not put large efforts into fixing the software.
~~However, I did look at the file you sent, and what struck me is that the coded event it failed on had a slash (/) in the event name. Would you mind trying with an .eaf file where events are coded using only standard characters?~~

Cheers,
Richard

**Comment by richardandersson** [comment]
Or it is likely not a problem with the event characters. ELAN has updated the format. Your file uses 3.0 and my software developed for 2.7. You could try installing an older ELAN version and see if you can load your 3.0 files and then export 2.7 files and see if that works.

**Comment by richardandersson** [comment]
I think I know what the problem is now. The software was unfortunately built with a bad assumption based on the project that it was developed for. It does not look through all tiers for all events to identify all time codes that can be referred to, so some are missed. That is what your error message is about: it tries to find a reference to an event that has not been parsed. It is possible to fix this, but requires some rewriting. So in all honesty, this will likely not happen anytime soon.

**Comment by richardandersson** [comment]
I think I fixed the issue. I was because your ELAN file used version 3.0, and the software was built for 2.7. Update and please try it again.
